In [1]:
import pandas as pd

df=pd.read_csv("../data/raw/IPL_Ball_by_Ball_2008_2022.csv")

df.head()

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals

In [2]:
df.shape

(225954, 17)

In [3]:
df.columns

Index(['ID', 'innings', 'overs', 'ballnumber', 'batter', 'bowler',
       'non-striker', 'extra_type', 'batsman_run', 'extras_run', 'total_run',
       'non_boundary', 'isWicketDelivery', 'player_out', 'kind',
       'fielders_involved', 'BattingTeam'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225954 entries, 0 to 225953
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ID                 225954 non-null  int64
 1   innings            225954 non-null  int64
 2   overs              225954 non-null  int64
 3   ballnumber         225954 non-null  int64
 4   batter             225954 non-null  object
 5   bowler             225954 non-null  object
 6   non-striker        225954 non-null  object
 7   extra_type         12049 non-null   object
 8   batsman_run        225954 non-null  int64
 9   extras_run         225954 non-null  int64
 10  total_run          225954 non-null  int64
 11  non_boundary       225954 non-null  int64
 12  isWicketDelivery   225954 non-null  int64
 13  player_out         11151 non-null   object
 14  kind               11151 non-null   object
 15  fielders_involved  7988 non-null    object
 16  BattingTeam        225954 non-null  object
dtypes: int64(9), object(8)
memory usage: 29.3+ MB

In [7]:
df.head(100)

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1312200,1,15,6,TA Boult,R Sai Kishore,R Parag,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
96,1312200,1,16,1,R Parag,LH Ferguson,TA Boult,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
97,1312200,1,16,2,TA Boult,LH Ferguson,R Parag,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
98,1312200,1,16,3,R Parag,LH Ferguson,TA Boult,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
99,1312200,1,16,4,TA Boult,LH Ferguson,R Parag,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals

###